# Generated by Django 5.1.3 on 2024-11-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naija_kitchen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
