# Generated by Django 5.1.3 on 2024-11-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naija_kitchen', '0004_restaurant_restaurant_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_category_per_restaurant'),
        ),
    ]
