# Generated by Django 5.1.3 on 2024-11-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naija_kitchen', '0006_alter_restaurant_restaurant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
