# Generated by Django 5.1.3 on 2024-11-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_restaurant_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
    ]
