# Generated by Django 5.1.3 on 2024-11-26 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_order_restaurant'),
        ('naija_kitchen', '0013_alter_restaurant_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='naija_kitchen.restaurant'),
        ),
    ]
